export {
  createSignal,
  createEffect,
  createMemo,
  createComputed,
  createRoot,
  onCleanup,
  batch,
  untrack,
  createStore,
  type SignalStore
} from './signal';

export {
  html,
  createElement,
  mount,
  render,
  fragment,
  when,
  each,
  createPortal
} from './template';

export {
  bindText,
  bindAttribute,
  bindClass,
  bindClasses,
  bindStyle,
  bindStyles,
  bindVisibility,
  bindDisabled,
  bindValue,
  bindChecked,
  bindList,
  createDOMElement,
  patchElement,
  createCustomEvent,
  dispatchCustomEvent,
  onCustomEvent,
  on,
  delegate,
  observeIntersection,
  observeResize,
  observeMutation,
  setAttributes,
  setStyles,
  addClass,
  removeClass,
  toggleClass,
  hasClass,
  replaceChildren,
  insertAdjacent,
  type DOMBinding,
  type ListBinding
} from './dom';

export {
  typedArrayPool,
  filterWithBitmap,
  sortWithIndices,
  binarySearch,
  findInsertionPoint,
  sumTypedArray,
  maxTypedArray,
  minTypedArray,
  averageTypedArray,
  copyTypedArray,
  fillTypedArray,
  bitwiseAnd,
  bitwiseOr,
  bitwiseXor,
  bitwiseNot,
  popcount32,
  countSetBits,
  setBit,
  clearBit,
  toggleBit,
  testBit,
  createBitmap,
  setBits,
  clearBits,
  getBitIndices,
  mergeSort,
  quickSelect,
  partialSort,
  type TypedArrayPool
} from './typed-arrays';

export {
  schedule,
  scheduleImmediate,
  scheduleHigh,
  scheduleNormal,
  scheduleLow,
  scheduleIdle,
  cancelTask,
  flushSync,
  clearQueue,
  getQueueLength,
  defer,
  nextTick,
  nextFrame,
  throttleFrame,
  debounceFrame,
  throttle,
  debounce,
  batch as batchTasks,
  runAfterPaint,
  whenIdle,
  cancelIdle
} from './scheduler';

export {
  createObjectPool,
  acquireChunkData,
  releaseChunkData,
  clearChunkDataPool,
  createBitset,
  setBit as setPoolBit,
  clearBit as clearPoolBit,
  testBit as testPoolBit,
  countSetBits as countPoolSetBits,
  calculateProgressFromBitset,
  createProgressTracker,
  type ObjectPool,
  type ChunkData,
  type ProgressTracker
} from './pool';

export {
  getTemplate,
  cloneTemplate,
  createIconSvg,
  BUTTON_TEMPLATE,
  PROGRESS_TEMPLATE,
  TOAST_TEMPLATE,
  PROCESSING_STATUS_TEMPLATE,
  DOWNLOAD_SECTION_TEMPLATE,
  CHUNK_ITEM_TEMPLATE,
  UPLOAD_ZONE_TEMPLATE,
  UPLOAD_DROP_ZONE_TEMPLATE,
  YOUTUBE_INPUT_TEMPLATE
} from './templates';
